// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8K4FlyzvrWTXw5xMrXeDrFGvnDPQOCkg',
    appId: '1:808422468031:android:911c803d63e92d5414990a',
    messagingSenderId: '808422468031',
    projectId: 'esp32-8db74',
    databaseURL: 'https://esp32-8db74-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-8db74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe69jdCceFdRJA7aNOCocx9gcYKjii8cM',
    appId: '1:808422468031:ios:7aece919a7b8303c14990a',
    messagingSenderId: '808422468031',
    projectId: 'esp32-8db74',
    databaseURL: 'https://esp32-8db74-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-8db74.appspot.com',
    iosClientId: '808422468031-buk922b8c7e12j3jmh59u14rnj6qm207.apps.googleusercontent.com',
    iosBundleId: 'com.example.madicalBox',
  );
}
